### ISSUE TITLE
Webrtc from chat does not work in chrome

### ISSUE THREAD

**Issue by Globik** [mdn/samples-server#42]
Operation error: failed to set remote answer sdp: failed to push down transport description: failed to set ssl role for the channel. Any thoughts?

**Comment by a2sheppy** [comment]
I will take a look at this, thanks. I'm not sure what's changed to cause this.

**Comment by Globik** [comment]
But in firefox works like a charm

**Comment by a2sheppy** [comment]
I have a vague notion that this is a thing I'm familiar with. I am going to look at this next, after lunch.

**Comment by medvedevden1s** [comment]
chome works fine v 58.0.3029.110 (64-bit)

**Comment by dbogatz** [comment]
@Globik 
That may happen if Firefox initiates the session (as server) and chrome is the client.
When chrome (later) creates a new offer (e.g. to add another stream/source) then this error occurs because chrome is not able to become the active server (creating an offer switches state to active/server).
